package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculadoraApp.idl
* jueves 17 de marzo de 2022 19H56' CET
*/

public interface CalculadoraOperations 
{
  float sumar (float n1, float n2);
  float restar (float n1, float n2);
  float multiplicar (float n1, float n2);
  float dividir (float n1, float n2);
  double raiz (double n1);
} // interface CalculadoraOperations
