package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculadoraApp.idl
* jueves 17 de marzo de 2022 11H50' CET
*/

public interface CalculadoraOperations 
{
  int somar (int n1, int n2);
  int substrair (int n1, int n2);
  int multiplicar (int n1, int n2);
  double dividir (int n1, int n2);
} // interface CalculadoraOperations
