module CalculadoraApp {
	interface Calculadora {
		float sumar(in float n1,in float n2);
		float restar(in float n1,in float n2);
		float multiplicar(in float n1,in float n2);
		float dividir(in float n1,in float n2);
		double raiz(in double n1);
	};
};